services:
  broker:
    image: eclipse-mosquitto:2
    ports: ["1883:1883"]
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=kwiatki_user
      - POSTGRES_PASSWORD=kwiatki_secret_pw
      - POSTGRES_DB=kwiatki_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  backend:
    build: ./backend
    environment:
      - MQTT_BROKER_URL=broker
      - DATABASE_URL=postgresql://kwiatki_user:kwiatki_secret_pw@db/kwiatki_db
      - JWT_SECRET=a_very_secure_secret_key_change_me_later # Add JWT Secret Variable
      - FLASK_DEBUG=True # Optional: Enable debug mode for development
    depends_on: [broker, db]
    ports: ["8000:8000"]
    volumes: # Add volume mapping for easier development (optional)
      - ./backend:/app

  sim:
    build: ./sim
    environment:
      - MQTT_HOST=broker
    depends_on: [broker]

volumes:
  mosquitto-data:
  postgres-data:
